- src/index.html
Added HTML files to project and connected them partially to index.html
> Feat(HTML) files

- README.md
> Feat(README) API

- src/catalog.html
- src/my-library.html
Update files HTML & removed unnecessary
> Fix(HTML) update files

- README.md
Added examples of writing commit on a project
> Docs(README) Documentation update

- src/sass/base/_colors.scss
Added colors to file base/_colors
> Style(SCSS) Code style edits (colors)

- src/sass/utils/_command.scss
> Fix(SASS) Error correction

- package-lock.json
- package.json
- src/js/api-key.js
- src/js/api-service.js
Update api-service.js
import { KEY } from './api-key.js';
Created api-key.js
Created api-key.js for key The Movie Database (TMDB)
Update api-service.js
I'm using the default export, since the named export is just a re-export from the Axios factory:
import axios from 'axios';
Addition axios (.json)
Addition new dependencies
Installing
Using npm:
$ npm install axios
> Api service

- src/partials/footer.html
- src/sass/layout/_footer.scss
> Feat(HTML & SCSS) animation

- src/js/catalog.js
Added rendering movies of the week in catalog
> added new functionality in catalog(JS)

- src/js/catalog.js
- src/js/stars.js
added function createStarRating in catalog(JS)
added file stars.js with svg stars
> added star rating in catalog(JS)

- src/js/cards-rendering.js
- src/js/catalog.js
adde cards-rendering.js file with movie card rendering deletid function renderMoviesCards from catalog.js
> cards-rendering(js)

- src/js/catalog-search-form.js
- src/partials/catalog-gallery.html
- src/sass/layout/_catalog-gallery.scss
>  Feat(HTML, SCSS, JS) Added new functionality

- src/index.js
- src/js/library-api-service.js
- src/js/my-library.js
- src/partials/my-library&load-more.html
- src/sass/layout/_header.scss
> my-library logic

- src/partials/hero.html
- src/sass/base/_colors.scss
- src/sass/layout/_hero.scss
Фиксит в герое падинги, и делает переключает героя между темной и светлой темой
> Vitalik hero

- src/js/catalog-search-form.js
- src/partials/catalog-gallery.html
- src/sass/layout/_catalog-gallery.scss
> Feat(HTML,SCSS,JS) Added new functionality

- src/partials/upcoming-mounth.html
> Feat(HTML) Added new functionality

- src/js/api-service-main.js
pagination add to api-service-main
> pagination

- src/js/cards-rendering.js
- src/js/catalog.js
> catalog(js)

- src/sass/layout/_catalog-gallery.scss
> Style(SCSS)

- src/js/upcoming-mounth.js
- src/sass/layout/_upcoming-mounth.scss
Вітання
Не поборов поки сплющену картинку на Мобілці
> Feat(JS+SASS) Added new functionality

- src/js/cards-rendering.js
> Revert(JS)

- src/js/cards-rendering.js
- src/sass/layout/_catalog-gallery.scss
Add card - rendered, catalog galery.
>  Feat(JS, SCSS) Added new functionality

- src/js/catalog-slider.js
> pagination catalog-slider.js

- src/js/catalog.js
> pagination (catalog.js)

- src/js/upcoming-mounth.js
- src/sass/layout/_upcoming-mounth.scss
JS - Change  IMG
SCSS - change auto
> Fix(JS+SCSS)

- src/js/cards-rendering.js
> cards-rendering.js

- src/js/cards-rendering.js
> Add js galery

- src/sass/layout/_catalog-gallery.scss
> Style(SCSS) Code style edits

- src/js/hero.js
Добавил рандомайзер . тепрь при каждой загрузке ходится рандомно первый из 15 слайд.
> random-first-slide
